reviews:
  profile: 'chill' # less aggressive than default

  request_changes_workflow: false # don't auto-block PRs

  high_level_summary: true
  poem: false
  diff_only: true # Stop reviewing old code that is not part of the PR

  instructions: >
    Do NOT suggest adding type annotations.
    Do NOT comment on missing return type hints.
    Focus on:
    - runtime correctness
    - security issues
    - performance issues
    - race conditions
    - architectural risks

  auto_review:
    enabled: true
    drafts: false # don't review draft PRs

  path_filters:
    - '!**/*.md'
    - '!docs/**'
    - '!**/*.json'
    - '!**/*.lock'
    - '!dist/**'
    - '!build/**'

tools:
  ruff:
    enabled: false # we already run this
